### ISSUE TITLE
Add-on logo 403

### ISSUE THREAD

**Issue by sungshon** [TheBeastLT/stremio-cdn-videos#3]
Hi, your add-ons logo image gives a 403 error and doesn't load in PMS.

https://github.com/sungshon/PimpMyStremio/blob/master/src/addonsList.json#L18

Is there any chance you could upload it somewhere else so i can update the image before the next release?

**Comment by TheBeastLT** [comment]
I don't seem to have any problem accessing the image from the web of from the PMS.
It's also available through https://cdn-videos.ga/static/images/logo.png

**Comment by sungshon** [comment]
i'll update it to https://cdn-videos.ga/static/images/logo.png

it might be due to the VPN, but it's the only image that seems to give an error, so better safe then sorry

btw, i'm working on getting source maps to work for clearer add-on errors, after which i'll do a final stable release (with a ton of bug fixes and new features), so release / announcement of PMS should hopefully be till this friday
